#!/bin/sh
#
# SPDX-License-Identifier: CDDL-1.0
#
# Copyright 2025 Peter Tribble
#
# build jingle
#

PATH=/usr/jdk/instances/jdk1.8.0/bin:$PATH
export PATH

JUMBLEDIR="../jumble"

#
# new PMD version has categories only
#
PMDCATRULES="security performance"
PMDCACHE="${HOME}/.pmd/cache.pkgview"

case $1 in
clean)
	rm -f $(find uk/co -type f -name '*.class')
	rm -f $(find . -type f -name '*~')
	rm -fr javadoc
	exit 0
	;;
pmd)
	RULESETS=""
	shift
	for RULE in $PMDCATRULES "$@"
	do
	    RULESETS="${RULESETS},category/java/${RULE}.xml"
	done
	RULESETS=${RULESETS/,/}
	if [ ! -d "${HOME}/.pmd" ]; then
	    mkdir -p "${HOME}/.pmd"
	fi
	pmd check --cache "${PMDCACHE}" -d uk -R "$RULESETS" --use-version java-1.8 2>/dev/null
	exit 0
	;;
javadoc)
    rm -fr javadoc
    mkdir javadoc
    javadoc -classpath ${JUMBLEDIR}/jumble.jar:. -d javadoc uk.co.petertribble.jingle
    ;;
esac

javac -Xlint -Xlint:-rawtypes -classpath ${JUMBLEDIR}/jumble.jar uk/co/petertribble/jingle/*.java

jar cf jingle.jar properties/*.properties $(find uk/co/petertribble/jingle -name '*.class')
